/*
Language: Vimscript
Author: James Cash <james.cash@occasionallycogent.com>
Description: Syntax highlighting for vimscript
*/

hljs.LANGUAGES.vimscript = {
  case_insensitive: true,
  defaultMode: {
    lexems: [hljs.IDENT_RE],
    contains: ['comment', 'number', 'string', 'symbol'],
    keywords: {
      'keyword': {
        'abs': 1,
        'acos': 1,
        'add': 1,
        'append': 1,
        'argc': 1,
        'argidx': 1,
        'argv': 1,
        'asin': 1,
        'atan': 1,
        'atan2': 1,
        'autocmd': 1,
        'browse': 1,
        'browsedir': 1,
        'bufexists': 1,
        'buflisted': 1,
        'bufloaded': 1,
        'bufname': 1,
        'bufnr': 1,
        'bufwinnr': 1,
        'byte2line': 1,
        'byteidx': 1,
        'call': 1,
        'ceil': 1,
        'changenr': 1,
        'char2nr': 1,
        'cindent': 1,
        'clearmatches': 1,
        'col': 1,
        'complete': 1,
        'complete_add': 1,
        'complete_check': 1,
        'confirm': 1,
        'copy': 1,
        'cos': 1,
        'cosh': 1,
        'count': 1,
        'cscope_connection': 1,
        'cursor': 1,
        'deepcopy': 1,
        'delete': 1,
        'did_filetype': 1,
        'diff_filler': 1,
        'diff_hlID': 1,
        'empty': 1,
        'escape': 1,
        'eval': 1,
        'eventhandler': 1,
        'executable': 1,
        'exists': 1,
        'exp': 1,
        'expand': 1,
        'expr8': 1,
        'extend': 1,
        'feedkeys': 1,
        'filereadable': 1,
        'filewritable': 1,
        'filter': 1,
        'finddir': 1,
        'findfile': 1,
        'float2nr': 1,
        'floor': 1,
        'fmod': 1,
        'fnameescape': 1,
        'fnamemodify': 1,
        'foldclosed': 1,
        'foldclosedend': 1,
        'foldlevel': 1,
        'foldtext': 1,
        'foldtextresult': 1,
        'foreground': 1,
        'garbagecollect': 1,
        'get': 1,
        'getbufline': 1,
        'getbufvar': 1,
        'getchar': 1,
        'getcharmod': 1,
        'getcmdline': 1,
        'getcmdpos': 1,
        'getcmdtype': 1,
        'getcwd': 1,
        'getfontname': 1,
        'getfperm': 1,
        'getfsize': 1,
        'getftime': 1,
        'getftype': 1,
        'getline': 1,
        'getloclist': 1,
        'getmatches': 1,
        'getpid': 1,
        'getpos': 1,
        'getqflist': 1,
        'getreg': 1,
        'getregtype': 1,
        'gettabvar': 1,
        'gettabwinvar': 1,
        'getwinposx': 1,
        'getwinposy': 1,
        'getwinvar': 1,
        'glob': 1,
        'globpath': 1,
        'has': 1,
        'has_key': 1,
        'haslocaldir': 1,
        'hasmapto': 1,
        'histadd': 1,
        'histdel': 1,
        'histget': 1,
        'histnr': 1,
        'hlID': 1,
        'hlexists': 1,
        'hostname': 1,
        'iconv': 1,
        'indent': 1,
        'index': 1,
        'input': 1,
        'inputdialog': 1,
        'inputlist': 1,
        'inputrestore': 1,
        'inputsave': 1,
        'inputsecret': 1,
        'insert': 1,
        'isdirectory': 1,
        'islocked': 1,
        'items': 1,
        'join': 1,
        'keys': 1,
        'len': 1,
        'libcall': 1,
        'libcallnr': 1,
        'line': 1,
        'line2byte': 1,
        'lispindent': 1,
        'localtime': 1,
        'log': 1,
        'log10': 1,
        'map': 1,
        'maparg': 1,
        'mapcheck': 1,
        'match': 1,
        'matchadd': 1,
        'matcharg': 1,
        'matchdelete': 1,
        'matchend': 1,
        'matchlist': 1,
        'matchstr': 1,
        'max': 1,
        'min': 1,
        'mkdir': 1,
        'mode': 1,
        'mzeval': 1,
        'nextnonblank': 1,
        'nr2char': 1,
        'pathshorten': 1,
        'pow': 1,
        'prevnonblank': 1,
        'printf': 1,
        'pumvisible': 1,
        'range': 1,
        'readfile': 1,
        'reltime': 1,
        'reltimestr': 1,
        'remote_expr': 1,
        'remote_foreground': 1,
        'remote_peek': 1,
        'remote_read': 1,
        'remote_send': 1,
        'remove': 1,
        'rename': 1,
        'repeat': 1,
        'resolve': 1,
        'reverse': 1,
        'round': 1,
        'search': 1,
        'searchdecl': 1,
        'searchpair': 1,
        'searchpairpos': 1,
        'searchpos': 1,
        'server2client': 1,
        'serverlist': 1,
        'setbufvar': 1,
        'setcmdpos': 1,
        'setline': 1,
        'setloclist': 1,
        'setmatches': 1,
        'setpos': 1,
        'setqflist': 1,
        'setreg': 1,
        'settabvar': 1,
        'settabwinvar': 1,
        'setwinvar': 1,
        'shellescape': 1,
        'simplify': 1,
        'sin': 1,
        'sinh': 1,
        'sort': 1,
        'soundfold': 1,
        'spellbadword': 1,
        'spellsuggest': 1,
        'split': 1,
        'sqrt': 1,
        'str2float': 1,
        'str2nr': 1,
        'strchars': 1,
        'strdisplaywidth': 1,
        'strftime': 1,
        'stridx': 1,
        'string': 1,
        'strlen': 1,
        'strpart': 1,
        'strridx': 1,
        'strtrans': 1,
        'strwidth': 1,
        'submatch': 1,
        'substitute': 1,
        'synID': 1,
        'synIDattr': 1,
        'synIDtrans': 1,
        'synconcealed': 1,
        'synstack': 1,
        'system': 1,
        'tabpagebuflist': 1,
        'tabpagenr': 1,
        'tabpagewinnr': 1,
        'tagfiles': 1,
        'taglist': 1,
        'tan': 1,
        'tanh': 1,
        'tempname': 1,
        'tolower': 1,
        'toupper': 1,
        'tr': 1,
        'trunc': 1,
        'type': 1,
        'undofile': 1,
        'undotree': 1,
        'values': 1,
        'virtcol': 1,
        'visualmode': 1,
        'winbufnr': 1,
        'wincol': 1,
        'winheight': 1,
        'winline': 1,
        'winnr': 1,
        'winrestcmd': 1,
        'winrestview': 1,
        'winsaveview': 1,
        'winwidth': 1,
        'writefile': 1
      },
      'built_in': {
        'endfunction': 1,
        'exe': 1,
        'execute': 1,
        'function!': 1,
        'function': 1,
        'imap': 1,
        'let': 1,
        'nmap': 1,
        'normal': 1,
        'vmap': 1
      }
    }
  },
  modes: [
    hljs.QUOTE_STRING_MODE,
    hljs.NUMBER_MODE,
    {
      className: 'comment',
      begin: '" (?![^\\n]*"[^\\n]*$)', end: '$'
    },
    {
      className: 'symbol',
      end: hljs.IMMEDIATE_RE,
      begin: [
        'BufAdd',
        'BufCreate',
        'BufDelete',
        'BufEnter',
        'BufFilePost',
        'BufFilePre',
        'BufHidden',
        'BufLeave',
        'BufNew',
        'BufNewFile',
        'BufRead',
        'BufReadCmd',
        'BufReadPost',
        'BufReadPre',
        'BufUnload',
        'BufWinEnter',
        'BufWinLeave',
        'BufWipeout',
        'BufWrite',
        'BufWriteCmd',
        'BufWritePost',
        'BufWritePre',
        'Cmd-event',
        'CmdwinEnter',
        'CmdwinLeave',
        'ColorScheme',
        'CursorHold',
        'CursorHoldI',
        'CursorMoved',
        'CursorMovedI',
        'EncodingChanged',
        'FileAppendCmd',
        'FileAppendPost',
        'FileAppendPre',
        'FileChangedRO',
        'FileChangedShell',
        'FileChangedShellPost',
        'FileEncoding',
        'FileReadCmd',
        'FileReadPost',
        'FileReadPre',
        'FileType',
        'FileWriteCmd',
        'FileWritePost',
        'FileWritePre',
        'FilterReadPost',
        'FilterReadPre',
        'FilterWritePost',
        'FilterWritePre',
        'FocusGained',
        'FocusLost',
        'FuncUndefined',
        'GUIEnter',
        'GUIFailed',
        'InsertChange',
        'InsertEnter',
        'InsertLeave',
        'MenuPopup',
        'QuickFixCmdPost',
        'QuickFixCmdPre',
        'RemoteReply',
        'SessionLoadPost',
        'ShellCmdPost',
        'ShellFilterPost',
        'SourceCmd',
        'SourcePre',
        'SpellFileMissing',
        'StdinReadPost',
        'StdinReadPre',
        'SwapExists',
        'Syntax',
        'TabEnter',
        'TabLeave',
        'TermChanged',
        'TermResponse',
        'User',
        'UserGettingBored',
        'VimEnter',
        'VimLeave',
        'VimLeavePre',
        'VimResized',
        'WinEnter',
        'WinLeave'
      ].join('|')
    }
  ]
};


